spring:
    application:
        name: service-registry
server:
    port: 9001
eureka:
    client:
        fetchRegistry: false
        registerWithEureka: false
    instance:
        hostname: localhost
