server:
    port: 9001
spring:
    application:
        name: service-registry
eureka:
    client:
        fetchRegistry: false
        registerWithEureka: false
    instance:
        hostname: localhost