version: "3.9"

services:
  service-registry:
    container_name: service-registry
    image: service-registry:latest
    build:
      dockerfile: ServiceRegistry.Dockerfile
    ports:
      - "9001:9001"
    networks:
      - msg-network
    deploy:
#      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    build:
      dockerfile: ApiGateway.Dockerfile
    ports:
      - "9000:9000"
    networks:
      - msg-network
    depends_on:
       service-registry:
#         condition: service_started
          condition: service_healthy
    deploy:
#      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  vat-rates:
    container_name: vat-rates-service
    image: vat-rates-service:latest
    build:
      dockerfile: VatRates.Dockerfile
    ports:
      - "9002:9002"
    networks:
      - msg-network
    depends_on:
      service-registry:
        condition: service_healthy
#         condition: service_started
      api-gateway:
        condition: service_healthy
#        condition: service_started

    deploy:
#      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  msg-network:
    driver: bridge

