spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888/config
#   import: optional:configserver:http://root:1234@localhost:8888/config
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9001/eureka/
