server:
  port: 9002
spring:
  application:
    name: VAT-RATES-SERVICE
eu:
  vatrates:
    url: https://euvatrates.com/rates.json
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9001/eureka/
springdoc:
  api-docs:
    path: /api-docs
