
spring:
    application:
        name: vat-rates-service
eu:
    vatrates:
        url: https://euvatrates.com/rates.json
server:
  port: 9002
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://service-registry:9001/eureka/
springdoc:
    api-docs:
        path: /api-docs
