server:
  port: 8888
  servlet:
    context-path: /config
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:9001/eureka/
spring:
  application:
    name: config-server
#  security:
#    user:
#      name: root
#      password: 1234
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/IdeaProjects/msg/config-repo/
          clone-on-start: true
#          uri: https://github.com/4ndr1j4/msg-repo
#          clone-on-start: true
#          default-label: config-repo
#          username: 4ndr1j4
#          password:

#     server:
#       git:
#         uri: https://github.com/4ndr1j4/msg.git
