server:
  port: 9003
  servlet:
    context-path: /config

management:
  health:
    livenessstate.enable: true
    readinessstate.enable: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9001/eureka/

spring:
  application:
    name: SERVICE-CONFIG
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/IdeaProjects/msg-microservices/config-repo
        default-label: config-repo